name: Update Version
on:
  push:
    branches:
      - main

jobs:
  update_label:
    runs-on: ubuntu-latest
    permissions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Increment Version
        run: |
          version=$(grep 'label' retype.yml | awk '{print $2}')
          incremented=$(echo "${version} + 0.1" | bc)
          sed -i "s/label: ${version}/label: ${incremented}/" retype.yml
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Update version
          push: true
