name: Update Version
on:
  push:
    branches:
      - main

jobs:
  update_label:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Increment Version
      run: |
        version=$(grep 'label' retype.yml | cut -d ' ' -f 4)
        major=$(echo $version | cut -d "." -f 1)
        minor=$(echo $version | cut -d "." -f 2)
        patch=$(echo $version | cut -d "." -f 3)
        patch=$((patch+1))
        new_version="$major.$minor.$patch"
        sed -i "s/label: ${version}/label: ${new_version}/" retype.yml
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: Update version
        push: true
