on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git reset --hard origin/main && git pull && pnpm i && pnpm run docs:build && cp -u -R /home/wotaku/htdocs/github/.vitepress/dist/* /home/wotaku/htdocs/wotaku.moe && exit"
    - name: Purge Cloudflare Cache
      run: |
        curl --request POST \
              --url https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache \
              --header 'Content-Type: application/json' \
              --header 'X-Auth-Email: $CF_ACCOUNT_MAIL' \
              --header 'Authorization: Bearer $CF_API_TOKEN' \
              --data '{"purge_everything": true}'
      env:
        CF_ZONE_ID: ${{ secrets.cf_zone_id }}
        CF_ACCOUNT_MAIL: ${{ secrets.cf_account_mail }}
        CF_API_TOKEN: ${{ secrets.cf_api_token }}
    - name: cleanup
      run: rm -rf ~/.ssh
